// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"database/sql"
	"time"
)

type ActionsLog struct {
	PowersinkID    int32
	Timestamp      time.Time
	DesiredAction  string
	DesiredReason  sql.NullString
	ExecutedAction string
	ExecutedReason sql.NullString
	Success        bool
	SuccessReason  sql.NullString
}

type AuthSession struct {
	UserID          string
	SessionToken    string
	AccessToken     string
	RefreshToken    string
	CreatedTime     time.Time
	LastRefreshTime time.Time
}

type EcobeeAccount struct {
	UserID          string
	EnphaseSystemID int64
	AccessToken     string
	RefreshToken    string
	CreatedTime     time.Time
	LastRefreshTime time.Time
}

type EcobeeThermostat struct {
	UserID          string
	EnphaseSystemID int64
	ThermostatID    string
}

type EnphaseSystem struct {
	UserID     string
	SystemID   int64
	Name       string
	PublicName string
	Timezone   string
}

type EnphaseTelemetry struct {
	UserID        string
	SystemID      int64
	StartAt       time.Time
	EndAt         time.Time
	InsertedAt    time.Time
	ProducedWatts int64
	ConsumedWatts int64
}

type Powersink struct {
	PowersinkID int32
	UserID      string
	SystemID    int64
	Created     time.Time
	Channel     string
	Recipient   sql.NullString
}
